In [1]:
import xarray as xr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import hvplot.xarray

In [2]:
lox = 10.0
hix = 14.0
stepx = 0.05
loy = 11.0
hiy = 15.0
stepy = 0.05

In [3]:
xpts = np.arange(lox, hix + stepx, stepx)
ypts = np.arange(loy, hiy + stepy, stepy)

In [4]:
phi0 = pd.read_csv('probe_wire_side_1.55mm_shim_fieldRaster_2019-02-05_1.csv', comment='#')

In [5]:
phi90 = pd.read_csv('probe_wire_side_1.55mm_shim_fieldRaster_2019-02-05_2.csv', comment='#')

In [22]:
phi0_dv = {}
phi90_dv = {}
for c in phi0.columns[:]:
    phi0_dv[c] = (["Ycoord", "Xcoord"], phi0[c].values.reshape(xpts.size, ypts.size))
    phi90_dv[c] = (["Ycoord", "Xcoord"], phi90[c].values.reshape(xpts.size, ypts.size))

In [23]:
coords = {'Xcoord': ('Xcoord', xpts), 'Ycoord': ('Ycoord', ypts)}

In [24]:
phi0_ds = xr.Dataset(phi0_dv, coords)
phi90_ds = xr.Dataset(phi90_dv, coords)

In [25]:
phi0_ds.X.hvplot()

:Image   [Ycoord,Xcoord]   (X)

In [26]:
phi0_ds.Yfield_avg.hvplot()

:Image   [Ycoord,Xcoord]   (Yfield_avg)

In [27]:
phi0_ds.Zfield_avg.hvplot()

:Image   [Ycoord,Xcoord]   (Zfield_avg)

In [28]:
phi0_ds.Xfield_avg.hvplot()

:Image   [Ycoord,Xcoord]   (Xfield_avg)

In [29]:
Zfield_mod = (phi90_ds.Zfield_avg**2 + phi0_ds.Zfield_avg**2)

In [30]:
Zfield_mod.hvplot(title = "Combined 0 and 90 Z field")

:Image   [Ycoord,Xcoord]   (Zfield_avg)

In [31]:
Zfield_mod.where(Zfield_mod == Zfield_mod.min(), drop=True)

<xarray.DataArray 'Zfield_avg' (Ycoord: 1, Xcoord: 1)>
array([[3.810781e-07]])
Coordinates:
  * Xcoord   (Xcoord) float64 11.95
  * Ycoord   (Ycoord) float64 14.45

In [32]:
Yfield_mod = (phi90_ds.Xfield_avg**2 + phi0_ds.Yfield_avg**2)

In [33]:
Yfield_mod.hvplot(title="Combined 0 and 90 Y field")

:Image   [Ycoord,Xcoord]   (value)

In [34]:
Yfield_mod.where(Yfield_mod == Yfield_mod.max(), drop=True)

<xarray.DataArray (Ycoord: 1, Xcoord: 1)>
array([[0.090482]])
Coordinates:
  * Xcoord   (Xcoord) float64 11.9
  * Ycoord   (Ycoord) float64 14.5

# From these, seems like the best point is $(13.5,12.9)$ with pretty strong corroboration beetween $Y$ maximum and $Z$ minimum field strength points

In [81]:
Xfield_mod = (phi90_ds.Yfield_avg**2 + phi0_ds.Xfield_avg**2)
Xfield_mod.hvplot(title="Combined 0 and 90 X field")

:Image   [Y,X]   (value)

In [78]:
Xfield_mod.where(Xfield_mod == Xfield_mod.min(), drop=True)

<xarray.DataArray (X: 1, Y: 1)>
array([[0.000185]])
Coordinates:
  * X        (X) float64 10.0
  * Y        (Y) float64 15.05